Here's some text from the template
changelog:
  categories:
  - title: Breaking Changes 🛠
    labels:
    - breaking-change
  - title: Features 🎉
    labels:
    - feature
    - documentation
  - title: Bug Fixes
    labels:
    - bug
  - title: Other Changes
    labels:
       - "*"
