name: preCD


on:
  workflow_dispatch:
  
  #push:
  #  tags:
  #3    - 'make-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Get new version number from tag
        run: |
          ref="${{github.ref}}"
          prefix="refs/tags/make-"
          suffix="-test"
          version=${ref#$prefix}
          version_pep440=${version%$suffix}
          echo "VERSION_NUMBER=$version" >> $GITHUB_ENV
          echo "VERSION_NUMBER_PEP440=$version_pep440" >> $GITHUB_ENV
          
          echo "${{ env.VERSION_NUMBER }}"
          echo "${{ env.VERSION_NUMBER_PEP440 }}"
  
      - name: Draft Release
        run: |
          gh release create ${{ env.VERSION_NUMBER }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
          
      # Get release notes 
      - name: Obtain notes and save to file
        run: |
          echo "$VERSION_NUMBER"
          gh api -H "Accept: application/vnd.github+json" /repos/anna-follestad-4ss/auto-release-demo/releases/tags/${{ env.VERSION_NUMBER }} -q ".body" > docs/new_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d %B %Y')"
          
      - name: ubuntu text adder
        run: |
          cd docs
          sed -i "3 i \ " release_notes.rst
          sed -i "3 i \ " release_notes.rst
          sed -i "3 i \ " release_notes.rst
          sed -i '3 r new_notes.txt' release_notes.rst
          sed -i "3 i ------------------------------------------------" release_notes.rst
          sed -i '3 i What is new in version ${{ env.VERSION_NUMBER  }} (${{ steps.date.outputs.date }})' release_notes.rst
          sed -i "3 i \ " release_notes.rst
          sed -i '9s/.*/ /' release_notes.rst
          
      - name: Setup Git
        run: |
          git config user.name 'anna-follestad-4ss'
          git config user.email 'anna.fehn.follestad@4subsea.com'
        
      - name: If prod, Push latest version to main 
        if: ${{ startswith(github.ref, 'refs/tags/make-v') && !endsWith(github.ref, '-test') }}
        run: |
          git add docs/release_notes.rst
          git commit -m "added latest release notes from autogen"
          git push origin main

      - name: Delete make-release
        # if: ${{ startswith(github.ref, 'refs/tags/make-') && endsWith(github.ref, '-test') }}
        run: |
          gh release delete make-${{ env.VERSION_NUMBER }} --cleanup-tag -y
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Move tag to include latest commit
        run: |
          git pull          
          git tag -d ${{ env.VERSION_NUMBER  }}
          git push origin :refs/tags/${{ env.VERSION_NUMBER  }}
          
          git tag ${{ env.VERSION_NUMBER  }}
          git push --tags
      
      - name: Publish drafted release
        run: |
          gh release edit ${{ env.VERSION_NUMBER  }} --draft=False
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}

          
          
        
