name: CD

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build sphinx pydata_sphinx_theme

      - name: Get new version number from tag
        run: |
          ref="${{github.ref}}"
          prefix="refs/tags/v"
          suffix="-test"
          version=${ref#$prefix}
          version=${version%$suffix}
          echo "VERSION_NUMBER=$version" >> $GITHUB_ENV

      - name: Build package
        run: python -m build --sdist --wheel --outdir ./dist

      - name: Build documentation
        run:  |
          pip install .
          sphinx-build -b html ./docs ./build/html

      - name: Publish package to TestPyPi
        # if: ${{ startswith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-test') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_KEY }}
          repository_url: https://test.pypi.org/legacy/
        
     

