name: CD - triggered by preCD 


on:
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    python -m pip install build sphinx pydata_sphinx_theme       
    
    
      - name: Get new version number from tag
        run: |
          git fetch -a
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: use env var
        run: echo ${{ env.GIT_TAG }}
        
      - name: Replace package version number
        run: |
          filename="src/YellowBanana/__init__.py"
          search_pattern="__version__ = \"0.0.1\""
          replacement_text="__version__ = \"${{ env.GIT_TAG }}\""
          echo replacement_text
          echo "2"
          echo $replacement_text
          sed -i "s/$search_pattern/$replacement_text/" "$filename"

        
        
        
      #- name: Build package
      #  run: python -m build --sdist --wheel --outdir ./dist

      #- name: Build documentation
      #  run:  |
      #    pip install .
      #    sphinx-build -b html ./docs ./build/html

      #- name: Publish package to TestPyPi
      #  # if: ${{ startswith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-test') }}
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    user: __token__
      #    password: ${{ secrets.PYPI_TEST_API_KEY }}
      #    repository_url: https://test.pypi.org/legacy/
      
      #- name: Upload documentation to TEST blob storage
      #  # if: ${{ startswith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-test') }}
      #  uses: azure/CLI@v1
      #  env:
      #    AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.FOURINSIGHTTEST_DOC_BLOB_CONNSTR }}
      #  with:
      #    inlineScript: |
      #      az storage blob delete-batch -s "\$web" --pattern "yellowbanana/python/docs/latest/*"
      #      az storage blob upload-batch -d "\$web" -s ./build/html --destination-path "yellowbanana/python/docs/latest"
      #      az storage blob upload-batch -d "\$web" -s ./build/html --destination-path "yellowbanana/python/docs/v$VERSION_NUMBER"
        
     
