
on:
  push:
    tags:
      - 'v*'
      
name: Create Release

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.access_token }}
        
      - name: Create Release
        run: |
          gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
  get-release-notes:
    name: Get automatically created release notes
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.access_token }}
        
      - name: Obtain notes and save to file
        run: |
          echo "hello again!"
          echo ""
          gh api -H "Accept: application/vnd.github+json" /repos/anna-follestad-4ss/auto-release-demo/releases/latest -q ".body" > docs/new_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git
        run: |
          git config user.name 'anna-follestad-4ss'
          git config user.email 'anna.fehn.follestad@4subsea.com'
        
      - name: Push latest version
        run: |
          git add .
          git commit -m "saved release notes from latest release to file "
          git push origin main
          
 
  write-ubuntu:
    runs-on: ubuntu-latest
    needs: get-release-notes
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.access_token }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d %B %Y')"
          
      - name: ubuntu text adder
        run: |
          cd docs
          sed -i "3 i \ " release_notes.rst
          sed -i "3 i \ " release_notes.rst
          sed -i "3 i \ " release_notes.rst
          sed -i '3 r new_notes.txt' release_notes.rst
          sed -i "3 i ------------------------------------------------" release_notes.rst
          sed -i '3 i What is new in version ${{ github.ref_name }} (${{ steps.date.outputs.date }})' release_notes.rst
          sed -i "3 i \ " release_notes.rst
          
          
  
      - name: Setup Git
        run: |
          git config user.name 'anna-follestad-4ss'
          git config user.email 'anna.fehn.follestad@4subsea.com'
        
      - name: Push latest version
        run: |
          git add docs/release_notes.rst
          git commit -m "added some text to release notes"
          git push origin main
  
        
  #write-windows:   
  #  runs-on: windows-latest 
  #  needs: get-release-notes
  #  
  #  steps:
  #    - name: Check out source
  #      uses: actions/checkout@v3
  #      with:
  #        ref: main
  #
  #    - name: third text adder
  #      id: add_more_text
  #      run: |
  #        chdir docs
  #        type release_notes.rst >> new_notes.txt
  #        type new_notes.txt > release_notes.rst
  # 
  #
  #    - name: Setup Git
  #      run: |
  #        git config user.name 'anna-follestad-4ss'
  #        git config user.email 'anna.fehn.follestad@4subsea.com'
  #      
  #    - name: Push latest version
  #      run: |
  #        git add docs/release_notes.rst
  #        git commit -m "added some text to release notes"
  #        git push origin main
          
          

        
